### ISSUE TITLE
ImportError onnxparser

### ISSUE THREAD

**Issue by kshamaramesh** [musicbeer/pytorch-tensorrt#2]
@musicbeer Can you provide me with the solution. Awaiting for your response

I just changed from tensorrt.parsers to from tensorrt.legacy.parsers. Then I was able to import the onnxparser.

However, after I imported the onnxparser, I got the following error.
  x = x.view(int(x.shape[0]), -1)
Traceback (most recent call last):
  File "model2trt.py", line 122, in <module>
    onnx_2_float32()
  File "model2trt.py", line 51, in onnx_2_float32
    apex = onnxparser.create_onnxconfig()
**AttributeError: type object 'onnxparser' has no attribute 'create_onnxconfig'**

**Comment by w956847136** [comment]
> @musicbeer Can you provide me with the solution. Awaiting for your response
> 
> I just changed from tensorrt.parsers to from tensorrt.legacy.parsers. Then I was able to import the onnxparser.
> 
> However, after I imported the onnxparser, I got the following error.
> x = x.view(int(x.shape[0]), -1)
> Traceback (most recent call last):
> File "model2trt.py", line 122, in
> onnx_2_float32()
> File "model2trt.py", line 51, in onnx_2_float32
> apex = onnxparser.create_onnxconfig()
> **AttributeError: type object 'onnxparser' has no attribute 'create_onnxconfig'**

I have same problem.!Have you solved the problem？

**Comment by musicbeer** [comment]
hello, this code is under tensorRT 4 api, not tensorRT 5

**Comment by musicbeer** [comment]
@kshamaramesh @w956847136

**Comment by Tian14267** [comment]
Do you know API in tensorRT 5.1 ? like..."**trt.infer.EntropyCalibrator**" in line 13 of **calib.py**
@musicbeer
